- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v2.5.0"
  hooks:
    - id: check-merge-conflict
    - id: debug-statements

- repo: local

  hooks:
    

    - id: black
      name: black
      entry: black
      language: system
      types: [python]
      args: [--target-version=py37]

    - id: autoflake
      name: autoflake
      entry: autoflake
      language: system
      types: [python]
      args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]

    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: [
            "--ignore=E203,E231,W503,PT013,C819,C818,C815,C814",
            #black
                # E203 whitespace before ':'
                # W503 line break before binary operator
            # flake8-pytest-style
                # PT013 found incorrect import of pytest, use simple 'import pytest' instead
            "--max-line-length=88",
            "--per-file-ignores=tests.py:S101",
            "--exclude=manage.py, */migrations/*"
            # S101 Use of assert detected
        ]

    - id: pyupgrade
      name: pyupgrade
      entry: pyupgrade
      language: system
      types: [python]
      args: [--py37-plus]

    - id: reorder-python-imports
      name: reorder-python-imports
      entry: reorder-python-imports
      language: system
      types: [python]
      args: [--py37-plus]

    - id: yesqa
      name: yesqa
      entry: yesqa
      language: system
      types: [python]

- repo: https://github.com/commitizen-tools/commitizen
  rev: master
  hooks:
    - id: commitizen
      stages: [commit-msg]
