[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.1"
tag_format = "v$minor.$major.$patch$prerelease"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "backend.project.settings"
python_files = "tests.py test_*.py *_tests.py"
