# Generated by Django 3.0.8 on 2020-07-11 16:56
from django.db import migrations

group_name = "managers"


def apply_migration(apps, schema_editor):
    Group = apps.get_model("users", "Group")
    Group.objects.create(name=group_name, is_staff=True)


def revert_migration(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name=group_name).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [migrations.RunPython(apply_migration, revert_migration)]
