# Generated by Django 3.0.8 on 2020-07-11 16:56
from django.db import migrations

groups = (
    {"name": "administrators", "is_staff": True},
    {"name": "managers", "is_staff": True},
    {"name": "users", "is_staff": False},
)


def apply_migration(apps, schema_editor):
    Group = apps.get_model("users", "Group")
    for group in groups:
        Group.objects.create(**group)


def revert_migration(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for group in groups:
        Group.objects.filter(**group).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [migrations.RunPython(apply_migration, revert_migration)]
