# Generated by Django 3.0.8 on 2020-07-11 22:14
from django.db import migrations

from backend.users import models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_adds_groups"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user", managers=[("objects", models.CustomUserManager()),],
        ),
    ]
